<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>bon</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?i)^\s*+(system_chart|cluster_chart|creation_chart|scenario_chart|event_chart|class_chart|static_diagram|dynamic_diagram).*</string>
	<key>foldingStopMarker</key>
	<string>(?i)^\s*+(end).*</string>
	<key>name</key>
	<string>BON</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(cluster_chart|scenario_chart|creation_chart|system_chart|class_chart|event_chart|static_diagram|dynamic_diagram|end|cluster|class|indexing|part|query|command|explanation|description|scenario|creator|creates|involves|event|incoming|outgoing|client|component|inherit|object|calls|deferred|reused|feature|action|constraint|ensure|require)\b</string>
			<key>name</key>
			<string>keyword.control.untitled</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\\n</string>
					<key>name</key>
					<string>constant.character.break</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(\-\-(.[\t\s\w\W]+))</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b.[A-Z0-9\_]+\b</string>
			<key>name</key>
			<string>entity.name.type.class</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(current|Current|result|Result)\b</string>
			<key>name</key>
			<string>support.language.bon</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(.[a-zA-Z\_]+\:)</string>
			<key>name</key>
			<string>variable.language.bon</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(=|!=|&lt;=|&gt;=|&lt;=&gt;|-&gt;|NOT|EQUAL)</string>
			<key>name</key>
			<string>keyword.operator.comparison.bon</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.bon</string>
	<key>uuid</key>
	<string>70C28272-71A2-48F5-BB3F-DC1310786790</string>
</dict>
</plist>
